version: "3.8"

services:
  pg_db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgres/data/
    ports:
      - 5432:5432
    env_file:
      - './.env'
  
  script:
    build: .
    restart: always
    command: python main.py
    network_mode: host
    depends_on:
      - pg_db
    env_file:
      - './.env'

volumes:
  postgres_data:
