version: "3.8"

services:
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgres/data/
    ports:
      - '5432:5432'
    env_file:
      - './.env'
  
  web:
    build: .
    restart: always
    command: python main.py
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  postgres_data:
